### ISSUE TITLE
TODO List ❗ 

### ISSUE THREAD

**Issue by JordanLeich** [JordanLeich/Superhero-Villain-Index#1]
- [ ] Keep adding in more heroes/villains.
- [x] Fix free for all mode bug where the winner is incorrectly displayed.
- [x] Fix request a character feature error.
- [x] Fix a bug where if blackheart is searched, the index cannot find him for some odd reason.
- [x] Add a function where the user can face off two heroes or villains against each other, whoever has the higher power ranking wins the battle.
- [x] Add unique traits to each hero and villain. Set traits to give each hero and villain advantages or disadvantages in versus battle mode.
- [x] Instead of just having 1v1 in versus mode. Add a 2v2 mode and a free for all mode.

# Contributing ✍️
- Here’s an easy and quick [video guide](https://youtu.be/waEb2c9NDL8) for learning how to contribute via GitHub

**Comment by kingkang00** [comment]
Hey would love to start working on this project. I am just getting back into Python programming and this project seems like the perfect place to start! Could you create a branch so I can start developing on some of the key features. Thanks.

**Comment by JordanLeich** [comment]
> Hey would love to start working on this project. I am just getting back into Python programming and this project seems like the perfect place to start! Could you create a branch so I can start developing on some of the key features. Thanks.

@kingkang00 awesome I'm looking forward to seeing what you add in. To get started, fork the project and then start working on your own version of the forked project and then once your done, create a pull request and I'll review it. Here's a video guide on how to do it if your wondering. https://youtu.be/waEb2c9NDL8

**Comment by kingkang00** [comment]
I cannot create a pull request because it is asking to compare from another branch within the repo or from a fork. I am not able to access the fork created on my account.

**Comment by JordanLeich** [comment]
> I cannot create a pull request because it is asking to compare from another branch within the repo or from a fork. I am not able to access the fork created on my account.
> 
> 

@kingkang00 Theres only 1 branch currently which is called the main branch. To help clarify, the main branch is the default branch or my own branch. I am unable to create another separate branch, only people who fork the project are able to be given their own unique branch. I see you also have not yet forked the project. Once you fork the project and make changes to your side on the branch, your changes can then be put into a pull request because GitHub will automatically notice that you have different branch changes than the main default branch I have. Hopefully that makes sense, if not let me know.

**Comment by JordanLeich** [comment]
@kingkang00 From what I can tell, I think you remade the project by making a new repository which means it's not connected to my original repository and that's why it's not letting you compare and make a pull request. Try to see if you can fork my project and then we'll go from there because then you'll be able to make a pull request.

**Comment by UnlivedMage** [comment]
Hey! I really like this project. I was wondering if you'd be open to adding a feature that gave the superheros/villains other traits like intelligence, magic, or things like that and maybe for the battle, it averages out the points of each skill for every character and the character with a higher average wins? I'd be willing to make a PR for this if you are open to the idea

**Comment by JordanLeich** [comment]
> Hey! I really like this project. I was wondering if you'd be open to adding a feature that gave the superheros/villains other traits like intelligence, magic, or things like that and maybe for the battle, it averages out the points of each skill for every character and the character with a higher average wins? I'd be willing to make a PR for this if you are open to the idea

@benmrtnz27 this sounds like an awesome idea! I'd be more than happy to have you add this feature in and I'll do my best work with you on it.

**Comment by mythicmrmun** [comment]
@JordanLeich I saw you considered storing all character data in a json file and importing them, I like this idea as the character database of characters grow it may be easier to maintain. Should this be listed in the TODO file?. Also as more people contribute each idea might need it's own issue and assignee to prevent multiple people working on the same thing.

**Comment by JordanLeich** [comment]
> @JordanLeich I saw you considered storing all character data in a json file and importing them, I like this idea as the character database of characters grow it may be easier to maintain. Should this be listed in the TODO file?. Also as more people contribute each idea might need it's own issue and assignee to prevent multiple people working on the same thing.

I don't have a ton of experience with json and how to connect it with the main program. I'm sure it's possible to store the data in a json file and then access the date through the index.py file but I'm just not sure how to do it. @mythicmrmun
